### ISSUE TITLE
Question: PtrTips to use a byte array for a const char*

### ISSUE THREAD

**Issue by deepakjois** [xlab/c-for-go#5] opened 2016-09-25 11:44 UTC
I have the following C function:

``` C
HB_EXTERN hb_blob_t *
hb_blob_create (const char        *data,
        unsigned int       length,
        hb_memory_mode_t   mode,
        void              *user_data,
        hb_destroy_func_t  destroy);

```

which is currently getting converted to:

``` Go
func BlobCreate(data string, length uint32, mode MemoryMode, userData unsafe.Pointer, destroy DestroyFunc) *Blob
```

What I really want is something like:

``` Go
func BlobCreate(data []byte, length uint32, mode MemoryMode, userData unsafe.Pointer, destroy DestroyFunc) *Blob
```

I tried something like:

```
  PtrTips:
    function:
      - {target: "_blob_create$", tips: [arr, 0, 0, 0, 0, 0]}
```

But I don’t really know what I am doing. To be honest, it is never really clarified in the manual anywhere what the `tips` array is supposed to be. I am assuming it is a mapping of the arguments to the function.

I any case that does not seem to have an effect.

**Comment by deepakjois** [comment] 2016-09-25 12:19
Ok, sorry about this. I seems like it is working. But this is happening to me a lot. I think I make a change and it does not take effect until I delete all the generated code and run cgogen _after_ that.

**Comment by deepakjois** [comment] 2016-09-25 12:26
Ok sorry…no its not working. But I have more details about the problem. See replication here:

https://github.com/deepakjois/cgogentest/tree/3af0a09204b78c0e6d01bc3282593fe3459ecdb7

Basically, `const char*` seem to get treated specially. If I change `const char*` to `char *`, then it works.

**Comment by xlab** [comment] 2016-09-25 12:39
Yes, that has been done intentionally, from the Go spec:

```
String types

A string value is a (possibly empty) sequence of bytes. Strings are immutable: once created, it is impossible to change the contents of a string. The predeclared string type is string.
```

That is exactly what `const char*` is. There is no allocation passing that value into C.
I'll reopen the issue add tips for that only if there will be some serious reason. Thanks for caring.

**Comment by deepakjois** [comment] 2016-09-25 13:11
I understand the default behavior. I could just convert a byte array into a string and pass it into the function to get around I guess.

You have already closed this issue, so I am not sure how much of a scope there is for discussion. I am not sure what qualifies as a ‘serious reason’. The harfbuzz package uses ‘const char *’ in many places to store binary blob-like data.  So a `const char *` is actually more than just a string. So it seems a bit arbitrary to make a mandatory  conversion to string. It is definitely a good default behavior, but it should be overridable. Otherwise, I will have to convert all binary data that I read from files into a string before I pass it to Harfbuzz. That seems very un-Go-like, and defeats the purpose of autogenerating the bindings.

**Comment by xlab** [comment] 2016-09-25 13:41
@deepakjois I fully understand your concern, the problem is that it cannot be easily overridden at this moment, the fix requires some fundamental changes and I'm not ready to do this right now.

I closed this issue but I'll keep this discussion in mind. I want to collect more issues like that so it will be a critical mass that will drive the change or someone would find a potential problem with performance or unsafe access that really affects the sanity.

As for "Go-like" principle, the API consistency is far more important than the Go-likeness of types, because they never be like Go ones. Of course that's just my opinion, but I just letting you know why is this. Converting an immutable `const char *` into a mutable type `[]byte` is the same thing as converting `long long` into `uint8`. These things cannot be "overriden" in manifest as well.

> Otherwise, I will have to convert all binary data that I read from files into a string before I pass it to Harfbuzz

That's not that hard to do.

```
func unsafeString(b []byte) string {
	hdr := (*sliceHeader)(unsafe.Pointer(&b))
	return *(*string)(unsafe.Pointer(&stringHeader{
		Data: hdr.Data,
		Len:  hdr.Len,
	}))
}

func ReadData(r io.Reader) string {
	buf, _ := io. ReadAll(r)
	return unsafeString(buf)
}
```

**Comment by deepakjois** [comment] 2016-09-25 13:59
Thanks for the clarification. It is good to hear that you are collecting the issues. Hopefully there is a good solution for this in the future.

As for your code, where does the `*sliceHeader` and `&stringHeader` come from?

**Comment by xlab** [comment] 2016-09-25 14:52
They usually are put in `cgo_helpers.go` when some string conversion occurs, so I expect that the generated package have it. Otherwise these are just renamed `reflect.SliceHeader` and `reflect.StringHeader`, I prefer to avoid including the reflect package and carry them around as private.

**Closed** 2017-02-19 13:52 UTC
Labels: enhancement, wontfix

**Comment by calle-gunnarsson** [comment] 2018-06-01 20:45
I have the same issue when trying to create go-bindings for libdivecomputer, it's an open source library for communication with dive computers from various manufacturers. And when it downloads the dive records from the dive computer it will pass the raw binary data to a callback as a `const unsigned char *data` and when the generated bindings use `packPUcharString` to convert this data into a string the resullt will be an empty string. 

Here is an [mplementation of the callback in C: [dctool_download.c](https://github.com/glance-/libdivecomputer/blob/master/examples/dctool_download.c#L57-L106)
And here is an example how is used: [shearwater_petrel.c](https://github.com/glance-/libdivecomputer/blob/master/src/shearwater_petrel.c#L255-L265)
